### ISSUE TITLE
Save NER with BERT model

### ISSUE THREAD

**Issue by lendamer** [marcellusruben/medium-resources#1]
Hello,

is there a way to save the model trained on the dataset? It seems like _torch.save(...)_ and _torch.load(...)_ doesn't work for me?

Best wishes

**Comment by mrubenw** [comment]
Hello,

to save the model you can use:

`torch.save(model.state_dict(), save_path)`

And then to load the model:

```
model = BertModel()
model.load_state_dict(torch.load(save_path))
model.eval()
````

and then you can use `model` to make a prediction.

**Comment by lendamer** [comment]
I trained the model again, evaluated it on a sentence and saved it according to your comment. 
If I load the model on another kernel and use the `evaluate_one_text(...)` function to predict the same sentence, the result is way different. 

Any idea how I can fix this and get consistent results?

**Comment by mrubenw** [comment]
In the notebook, the model was trained only with the first 1000 data and 5 epochs for demonstration purpose. To get a consistent result from the trained model, you need to train it with more data and more epochs.
